CREATE TABLE `wp_products_snapshot` (
  `product_id` BIGINT UNSIGNED NOT NULL,
  `product_name` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `product_type` VARCHAR(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `product_status` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'active',
  `product_url` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `product_image_url` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `min_price` INT UNSIGNED NOT NULL DEFAULT 0,
  `min_prepayment_person_count` SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  `discount_data` LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `product_hood` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `product_brand` JSON DEFAULT NULL,
  `product_city` JSON DEFAULT NULL,
  `product_area` JSON DEFAULT NULL,
  `product_tags` JSON DEFAULT NULL,
  `comments_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `rate` DECIMAL(4,2) NOT NULL DEFAULT 0.00,
  `schedule` JSON DEFAULT NULL,
  `owner_id` BIGINT UNSIGNED DEFAULT NULL,
  `manager_id` BIGINT UNSIGNED DEFAULT NULL,
  `rank_popular` INT UNSIGNED DEFAULT 0,
  `rank_hottest` INT UNSIGNED DEFAULT 0,
  `rank_topsale` INT UNSIGNED DEFAULT 0,
  PRIMARY KEY (`product_id`),
  KEY `idx_product_status` (`product_status`),
  KEY `idx_hood` (`product_hood`(32)),
  KEY `idx_min_price` (`min_price`),
  KEY `idx_rate` (`rate`),
  KEY `idx_comments_count` (`comments_count`),
  KEY `idx_rank_popular` (`rank_popular`),
  KEY `idx_rank_hottest` (`rank_hottest`),
  KEY `idx_rank_topsale` (`rank_topsale`),
  KEY `idx_owner` (`owner_id`),
  KEY `idx_manager` (`manager_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
