<?php
add_action( 'acf/include_fields', function () {
    if ( ! function_exists( 'acf_add_local_field_group' ) ) {
        return;
    }

    acf_add_local_field_group( [
        'key'                   => 'group_67cefab615ee8',
        'title'                 => 'اطلاعات دسته بندی',
        'fields'                => [
            [
                'key'               => 'field_67cefab46a18f',
                'label'             => 'اسلایدر',
                'name'              => 'slider',
                'aria-label'        => '',
                'type'              => 'repeater',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
                'layout'            => 'table',
                'pagination'        => 0,
                'min'               => 0,
                'max'               => 0,
                'collapsed'         => '',
                'button_label'      => 'سطر جدید',
                'rows_per_page'     => 20,
                'sub_fields'        => [
                    [
                        'key'               => 'field_67cefacf6a190',
                        'label'             => 'تصویر دسکتاپ',
                        'name'              => 'desktop-image',
                        'aria-label'        => '',
                        'type'              => 'image',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => [
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ],
                        'return_format'     => 'array',
                        'library'           => 'all',
                        'min_width'         => '',
                        'min_height'        => '',
                        'min_size'          => '',
                        'max_width'         => '',
                        'max_height'        => '',
                        'max_size'          => '',
                        'mime_types'        => '',
                        'allow_in_bindings' => 0,
                        'preview_size'      => 'medium',
                        'parent_repeater'   => 'field_67cefab46a18f',
                    ],
                    [
                        'key'               => 'field_67d197a46a18a',
                        'label'             => 'تصویر موبایل',
                        'name'              => 'mobile-image',
                        'aria-label'        => '',
                        'type'              => 'image',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => [
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ],
                        'return_format'     => 'array',
                        'library'           => 'all',
                        'min_width'         => '',
                        'min_height'        => '',
                        'min_size'          => '',
                        'max_width'         => '',
                        'max_height'        => '',
                        'max_size'          => '',
                        'mime_types'        => '',
                        'allow_in_bindings' => 0,
                        'preview_size'      => 'medium',
                        'parent_repeater'   => 'field_67cefab46a18f',
                    ],
                    [
                        'key'               => 'field_67cefada6a191',
                        'label'             => 'لینک',
                        'name'              => 'link',
                        'aria-label'        => '',
                        'type'              => 'text',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => [
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ],
                        'default_value'     => '',
                        'allow_in_bindings' => 0,
                        'placeholder'       => '',
                        'parent_repeater'   => 'field_67cefab46a18f',
                    ],
                    [
                        'key'               => 'field_67cefada6a1911',
                        'label'             => 'عنوان',
                        'name'              => 'title',
                        'aria-label'        => '',
                        'type'              => 'text',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => [
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ],
                        'default_value'     => '',
                        'allow_in_bindings' => 0,
                        'placeholder'       => '',
                        'parent_repeater'   => 'field_67cefab46a18f',
                    ],
                ],
            ],
            [
                'key'               => 'field_67cefb11dcb1b',
                'label'             => 'توضیحات کوتاه',
                'name'              => 'short-description',
                'aria-label'        => '',
                'type'              => 'textarea',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
                'default_value'     => '',
                'maxlength'         => '',
                'allow_in_bindings' => 0,
                'rows'              => '',
                'placeholder'       => '',
                'new_lines'         => '',
            ],
            [
                'key'               => 'field_67cefb26dcb1c',
                'label'             => 'سوالات متداول صفحه',
                'name'              => 'faq',
                'aria-label'        => '',
                'type'              => 'repeater',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
                'layout'            => 'table',
                'pagination'        => 0,
                'min'               => 0,
                'max'               => 0,
                'collapsed'         => '',
                'button_label'      => 'سطر جدید',
                'rows_per_page'     => 20,
                'sub_fields'        => [
                    [
                        'key'               => 'field_67cefb37dcb1d',
                        'label'             => 'عنوان',
                        'name'              => 'title',
                        'aria-label'        => '',
                        'type'              => 'text',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => [
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ],
                        'default_value'     => '',
                        'maxlength'         => '',
                        'allow_in_bindings' => 0,
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                        'parent_repeater'   => 'field_67cefb26dcb1c',
                    ],
                    [
                        'key'               => 'field_67cefb3fdcb1e',
                        'label'             => 'توضیحات',
                        'name'              => 'description',
                        'aria-label'        => '',
                        'type'              => 'wysiwyg',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => [
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ],
                        'default_value'     => '',
                        'allow_in_bindings' => 0,
                        'tabs'              => 'all',
                        'toolbar'           => 'full',
                        'media_upload'      => 1,
                        'delay'             => 0,
                        'parent_repeater'   => 'field_67cefb26dcb1c',
                    ],
                ],
            ],
            [
                'key'               => 'field_67cefef45564b',
                'label'             => 'لینک ویدئو',
                'name'              => 'video',
                'aria-label'        => '',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
                'default_value'     => '',
                'maxlength'         => '',
                'allow_in_bindings' => 0,
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
            ],
            [
                'key'               => 'field_67cf0109cde73',
                'label'             => 'آیکن',
                'name'              => 'icon',
                'aria-label'        => '',
                'type'              => 'image',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
                'return_format'     => 'array',
                'library'           => 'all',
                'min_width'         => '',
                'min_height'        => '',
                'min_size'          => '',
                'max_width'         => '',
                'max_height'        => '',
                'max_size'          => '',
                'mime_types'        => '',
                'allow_in_bindings' => 0,
                'preview_size'      => 'medium',
            ],
        ],
        'location'              => [
            [
                [
                    'param'    => 'taxonomy',
                    'operator' => '==',
                    'value'    => 'product_cat',
                ],
            ],
            [
                [
                    'param'    => 'taxonomy',
                    'operator' => '==',
                    'value'    => 'product_tag',
                ],
            ],
            [
                [
                    'param'    => 'post_type',
                    'operator' => '==',
                    'value'    => 'page',
                ],
            ],
        ],
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => true,
        'description'           => '',
        'show_in_rest'          => 0,
    ] );
} );

