/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { DateChangeDetail } from "./components/range-datepicker/range-datepicker";
export { DateChangeDetail } from "./components/range-datepicker/range-datepicker";
export namespace Components {
    interface EzAccordion {
    }
    interface EzAccordionItem {
        "label": string;
        /**
          * @default false
         */
        "open": boolean;
    }
    interface EzAutocomplete {
        /**
          * @default 300
         */
        "debounce": number;
        /**
          * @default false
         */
        "loading": boolean;
        /**
          * @default 'جستجو...'
         */
        "placeholder": string;
        /**
          * @default []
         */
        "results": string | any[];
        /**
          * @default ''
         */
        "value": string;
    }
    interface EzBadge {
        "sysBg": string;
        "sysColor": string;
        /**
          * @default 'default'
         */
        "variant": 'default' | 'success' | 'warning' | 'danger' | 'info' | 'custom';
    }
    interface EzBannerSlider {
        /**
          * @default []
         */
        "items": string | any[];
        /**
          * @default 'normal'
         */
        "sliderModel": 'wide' | 'normal';
    }
    interface EzBlogCard {
        "href"?: string;
        /**
          * @default false
         */
        "isSlide"?: boolean;
    }
    /**
     * EZ Brand Card — displays brand info with hover effects.
     * Used in brand archive and search results.
     * Props (from AJAX endpoint):
     *   - brandId: number - Brand ID
     *   - title: string - Brand name
     *   - slug: string - URL slug for /brand/{slug}
     *   - logo: string - Logo URL
     *   - score: number - Score (0-100)
     *   - reputation: number - Reputation (0-5 scale)
     *   - address: string - Brand address/location
     *   - gameCount: number - Number of games
     */
    interface EzBrandCard {
        /**
          * Brand address/location
         */
        "address": string;
        /**
          * Brand ID
         */
        "brandId": number;
        /**
          * @deprecated Use `title` instead
         */
        "brandName": string;
        /**
          * @deprecated Use `gameCount`
         */
        "count": number;
        /**
          * Number of games/products
         */
        "gameCount": number;
        /**
          * @deprecated Use `logo`
         */
        "imageSrc": string;
        /**
          * @deprecated Use slug-based link
         */
        "link": string;
        /**
          * Logo URL (primary)
         */
        "logo": string;
        /**
          * @deprecated Use `logo` instead
         */
        "logoUrl": string;
        /**
          * @deprecated Use `title`
         */
        "name": string;
        /**
          * @deprecated Use `reputation` instead
         */
        "rating": number;
        /**
          * Reputation (0-5 scale)
         */
        "reputation": number;
        /**
          * Score (0-100 scale)
         */
        "score": number;
        /**
          * Brand slug for URL
         */
        "slug": string;
        /**
          * Brand title/name (primary)
         */
        "title": string;
    }
    interface EzBreadcrumb {
        /**
          * @default []
         */
        "items": string | any[];
    }
    interface EzButton {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "loading": boolean;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * @default 'primary'
         */
        "variant": 'primary' | 'secondary' | 'outline' | 'ghost' | 'danger';
        /**
          * @default false
         */
        "wFull": boolean;
    }
    interface EzCollectionCard {
        "collectionTitle": string;
        /**
          * @default []
         */
        "images": string | string[];
        /**
          * @default 0
         */
        "likes": number;
        "link": string;
    }
    interface EzCommentItemPost {
    }
    interface EzCommentItemProduct {
        /**
          * @default 0
         */
        "rating": number;
        /**
          * @default false
         */
        "verified": boolean;
    }
    interface EzDropdown {
        /**
          * @default `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="6,9 12,15 18,9"></polyline></svg>`
         */
        "icon": string;
        /**
          * @default 'انتخاب کنید'
         */
        "label": string;
    }
    interface EzDropdownItem {
        /**
          * @default false
         */
        "selected": boolean;
        "value": any;
    }
    interface EzInput {
        "label": string;
        "name": string;
        "placeholder": string;
        /**
          * @default false
         */
        "readonly": boolean;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default 'text'
         */
        "type": string;
        "value": string;
    }
    interface EzLoading {
        /**
          * @default 'text-primary-500'
         */
        "color": string;
        "message"?: string;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg' | 'xl';
        /**
          * @default 'spinner'
         */
        "type": 'spinner' | 'dots' | 'circle';
    }
    interface EzModal {
        /**
          * @default true
         */
        "closeOnOverlayClick": boolean;
        /**
          * @default false
         */
        "isOpen": boolean;
        "modalTitle": string;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg' | 'xl';
    }
    interface EzPagination {
        /**
          * @default 1
         */
        "currentPage": number;
        /**
          * @default 1
         */
        "totalPages": number;
    }
    interface EzProductCard {
        "address"?: string;
        "href"?: string;
        "imageUrl"?: string;
        /**
          * @default false
         */
        "isSlide"?: boolean;
        "price"?: string;
        "productId"?: string | number;
        /**
          * عنوان محصول (از سرور؛ در HTML به‌صورت product-title پاس داده می‌شود تا با titleٔ رزروشده تداخل نداشته باشد).
         */
        "productTitle"?: string;
        "status"?: string;
    }
    interface EzRangeDatepicker {
        /**
          * انتخاب بازه (true) یا تک روز (false). از HTML: allow-range یا allow-range="false"
          * @default true
         */
        "allowRange": string | boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        "disabledDates"?: string[];
        "endDate"?: string;
        "maxDate"?: string;
        "minDate"?: string;
        /**
          * @default 'dateRange'
         */
        "name": string;
        /**
          * @default false
         */
        "persianNumbers": boolean;
        /**
          * @default 'انتخاب بازه تاریخ'
         */
        "placeholder": string;
        /**
          * @default false
         */
        "required": boolean;
        "startDate"?: string;
        /**
          * @default '#3b82f6'
         */
        "themeColor": string;
    }
    interface EzSansItem {
        "session": any;
    }
    interface EzSansList {
        /**
          * API endpoint for fetching sessions (e.g. admin-ajax.php?action=ez_sanses or custom).
          * @default ''
         */
        "apiEndpoint": string;
        "productId": string | number;
    }
    interface EzSelect {
        "label": string;
        /**
          * @default 'single'
         */
        "mode": 'single' | 'multiple';
        "name": string;
        /**
          * @default []
         */
        "options": string | any[];
        /**
          * @default 'انتخاب کنید'
         */
        "placeholder": string;
        /**
          * @default false
         */
        "searchable": boolean;
        "value": string | string[];
    }
    /**
     * EZ Skeleton - Placeholder loader for content that's being fetched.
     * Use as a wrapper or with predefined type props for common patterns.
     */
    interface EzSkeleton {
        /**
          * Show animation pulse effect
          * @default true
         */
        "animate": boolean;
        /**
          * Number of items to show (for list/card types)
          * @default 3
         */
        "count": number;
        /**
          * Predefined skeleton type: card, list, text, avatar
          * @default 'custom'
         */
        "type": 'card' | 'list' | 'text' | 'avatar' | 'custom';
    }
    interface EzTab {
        /**
          * @default false
         */
        "active": boolean;
        "label": string;
        "tabId": string;
    }
    interface EzTable {
        "caption": string;
        /**
          * @default []
         */
        "columns": string | any[];
        /**
          * @default false
         */
        "loading": boolean;
        /**
          * @default 5
         */
        "skeletonCount": number;
    }
    interface EzTableCell {
    }
    interface EzTableRow {
    }
    interface EzTabs {
        "activeTab": string;
    }
}
export interface EzAutocompleteCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEzAutocompleteElement;
}
export interface EzDropdownCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEzDropdownElement;
}
export interface EzDropdownItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEzDropdownItemElement;
}
export interface EzModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEzModalElement;
}
export interface EzPaginationCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEzPaginationElement;
}
export interface EzRangeDatepickerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEzRangeDatepickerElement;
}
export interface EzSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEzSelectElement;
}
export interface EzTabsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEzTabsElement;
}
declare global {
    interface HTMLEzAccordionElement extends Components.EzAccordion, HTMLStencilElement {
    }
    var HTMLEzAccordionElement: {
        prototype: HTMLEzAccordionElement;
        new (): HTMLEzAccordionElement;
    };
    interface HTMLEzAccordionItemElement extends Components.EzAccordionItem, HTMLStencilElement {
    }
    var HTMLEzAccordionItemElement: {
        prototype: HTMLEzAccordionItemElement;
        new (): HTMLEzAccordionItemElement;
    };
    interface HTMLEzAutocompleteElementEventMap {
        "search": string;
        "selection": any;
    }
    interface HTMLEzAutocompleteElement extends Components.EzAutocomplete, HTMLStencilElement {
        addEventListener<K extends keyof HTMLEzAutocompleteElementEventMap>(type: K, listener: (this: HTMLEzAutocompleteElement, ev: EzAutocompleteCustomEvent<HTMLEzAutocompleteElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLEzAutocompleteElementEventMap>(type: K, listener: (this: HTMLEzAutocompleteElement, ev: EzAutocompleteCustomEvent<HTMLEzAutocompleteElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLEzAutocompleteElement: {
        prototype: HTMLEzAutocompleteElement;
        new (): HTMLEzAutocompleteElement;
    };
    interface HTMLEzBadgeElement extends Components.EzBadge, HTMLStencilElement {
    }
    var HTMLEzBadgeElement: {
        prototype: HTMLEzBadgeElement;
        new (): HTMLEzBadgeElement;
    };
    interface HTMLEzBannerSliderElement extends Components.EzBannerSlider, HTMLStencilElement {
    }
    var HTMLEzBannerSliderElement: {
        prototype: HTMLEzBannerSliderElement;
        new (): HTMLEzBannerSliderElement;
    };
    interface HTMLEzBlogCardElement extends Components.EzBlogCard, HTMLStencilElement {
    }
    var HTMLEzBlogCardElement: {
        prototype: HTMLEzBlogCardElement;
        new (): HTMLEzBlogCardElement;
    };
    /**
     * EZ Brand Card — displays brand info with hover effects.
     * Used in brand archive and search results.
     * Props (from AJAX endpoint):
     *   - brandId: number - Brand ID
     *   - title: string - Brand name
     *   - slug: string - URL slug for /brand/{slug}
     *   - logo: string - Logo URL
     *   - score: number - Score (0-100)
     *   - reputation: number - Reputation (0-5 scale)
     *   - address: string - Brand address/location
     *   - gameCount: number - Number of games
     */
    interface HTMLEzBrandCardElement extends Components.EzBrandCard, HTMLStencilElement {
    }
    var HTMLEzBrandCardElement: {
        prototype: HTMLEzBrandCardElement;
        new (): HTMLEzBrandCardElement;
    };
    interface HTMLEzBreadcrumbElement extends Components.EzBreadcrumb, HTMLStencilElement {
    }
    var HTMLEzBreadcrumbElement: {
        prototype: HTMLEzBreadcrumbElement;
        new (): HTMLEzBreadcrumbElement;
    };
    interface HTMLEzButtonElement extends Components.EzButton, HTMLStencilElement {
    }
    var HTMLEzButtonElement: {
        prototype: HTMLEzButtonElement;
        new (): HTMLEzButtonElement;
    };
    interface HTMLEzCollectionCardElement extends Components.EzCollectionCard, HTMLStencilElement {
    }
    var HTMLEzCollectionCardElement: {
        prototype: HTMLEzCollectionCardElement;
        new (): HTMLEzCollectionCardElement;
    };
    interface HTMLEzCommentItemPostElement extends Components.EzCommentItemPost, HTMLStencilElement {
    }
    var HTMLEzCommentItemPostElement: {
        prototype: HTMLEzCommentItemPostElement;
        new (): HTMLEzCommentItemPostElement;
    };
    interface HTMLEzCommentItemProductElement extends Components.EzCommentItemProduct, HTMLStencilElement {
    }
    var HTMLEzCommentItemProductElement: {
        prototype: HTMLEzCommentItemProductElement;
        new (): HTMLEzCommentItemProductElement;
    };
    interface HTMLEzDropdownElementEventMap {
        "selectionChange": any;
    }
    interface HTMLEzDropdownElement extends Components.EzDropdown, HTMLStencilElement {
        addEventListener<K extends keyof HTMLEzDropdownElementEventMap>(type: K, listener: (this: HTMLEzDropdownElement, ev: EzDropdownCustomEvent<HTMLEzDropdownElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLEzDropdownElementEventMap>(type: K, listener: (this: HTMLEzDropdownElement, ev: EzDropdownCustomEvent<HTMLEzDropdownElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLEzDropdownElement: {
        prototype: HTMLEzDropdownElement;
        new (): HTMLEzDropdownElement;
    };
    interface HTMLEzDropdownItemElementEventMap {
        "optionSelect": { value: any; text: string };
    }
    interface HTMLEzDropdownItemElement extends Components.EzDropdownItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLEzDropdownItemElementEventMap>(type: K, listener: (this: HTMLEzDropdownItemElement, ev: EzDropdownItemCustomEvent<HTMLEzDropdownItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLEzDropdownItemElementEventMap>(type: K, listener: (this: HTMLEzDropdownItemElement, ev: EzDropdownItemCustomEvent<HTMLEzDropdownItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLEzDropdownItemElement: {
        prototype: HTMLEzDropdownItemElement;
        new (): HTMLEzDropdownItemElement;
    };
    interface HTMLEzInputElement extends Components.EzInput, HTMLStencilElement {
    }
    var HTMLEzInputElement: {
        prototype: HTMLEzInputElement;
        new (): HTMLEzInputElement;
    };
    interface HTMLEzLoadingElement extends Components.EzLoading, HTMLStencilElement {
    }
    var HTMLEzLoadingElement: {
        prototype: HTMLEzLoadingElement;
        new (): HTMLEzLoadingElement;
    };
    interface HTMLEzModalElementEventMap {
        "close": void;
    }
    interface HTMLEzModalElement extends Components.EzModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLEzModalElementEventMap>(type: K, listener: (this: HTMLEzModalElement, ev: EzModalCustomEvent<HTMLEzModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLEzModalElementEventMap>(type: K, listener: (this: HTMLEzModalElement, ev: EzModalCustomEvent<HTMLEzModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLEzModalElement: {
        prototype: HTMLEzModalElement;
        new (): HTMLEzModalElement;
    };
    interface HTMLEzPaginationElementEventMap {
        "pageChange": number;
    }
    interface HTMLEzPaginationElement extends Components.EzPagination, HTMLStencilElement {
        addEventListener<K extends keyof HTMLEzPaginationElementEventMap>(type: K, listener: (this: HTMLEzPaginationElement, ev: EzPaginationCustomEvent<HTMLEzPaginationElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLEzPaginationElementEventMap>(type: K, listener: (this: HTMLEzPaginationElement, ev: EzPaginationCustomEvent<HTMLEzPaginationElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLEzPaginationElement: {
        prototype: HTMLEzPaginationElement;
        new (): HTMLEzPaginationElement;
    };
    interface HTMLEzProductCardElement extends Components.EzProductCard, HTMLStencilElement {
    }
    var HTMLEzProductCardElement: {
        prototype: HTMLEzProductCardElement;
        new (): HTMLEzProductCardElement;
    };
    interface HTMLEzRangeDatepickerElementEventMap {
        "dateChanged": DateChangeDetail;
        "dateCleared": void;
        "calendarOpened": void;
        "calendarClosed": void;
    }
    interface HTMLEzRangeDatepickerElement extends Components.EzRangeDatepicker, HTMLStencilElement {
        addEventListener<K extends keyof HTMLEzRangeDatepickerElementEventMap>(type: K, listener: (this: HTMLEzRangeDatepickerElement, ev: EzRangeDatepickerCustomEvent<HTMLEzRangeDatepickerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLEzRangeDatepickerElementEventMap>(type: K, listener: (this: HTMLEzRangeDatepickerElement, ev: EzRangeDatepickerCustomEvent<HTMLEzRangeDatepickerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLEzRangeDatepickerElement: {
        prototype: HTMLEzRangeDatepickerElement;
        new (): HTMLEzRangeDatepickerElement;
    };
    interface HTMLEzSansItemElement extends Components.EzSansItem, HTMLStencilElement {
    }
    var HTMLEzSansItemElement: {
        prototype: HTMLEzSansItemElement;
        new (): HTMLEzSansItemElement;
    };
    interface HTMLEzSansListElement extends Components.EzSansList, HTMLStencilElement {
    }
    var HTMLEzSansListElement: {
        prototype: HTMLEzSansListElement;
        new (): HTMLEzSansListElement;
    };
    interface HTMLEzSelectElementEventMap {
        "selectionChange": any;
    }
    interface HTMLEzSelectElement extends Components.EzSelect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLEzSelectElementEventMap>(type: K, listener: (this: HTMLEzSelectElement, ev: EzSelectCustomEvent<HTMLEzSelectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLEzSelectElementEventMap>(type: K, listener: (this: HTMLEzSelectElement, ev: EzSelectCustomEvent<HTMLEzSelectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLEzSelectElement: {
        prototype: HTMLEzSelectElement;
        new (): HTMLEzSelectElement;
    };
    /**
     * EZ Skeleton - Placeholder loader for content that's being fetched.
     * Use as a wrapper or with predefined type props for common patterns.
     */
    interface HTMLEzSkeletonElement extends Components.EzSkeleton, HTMLStencilElement {
    }
    var HTMLEzSkeletonElement: {
        prototype: HTMLEzSkeletonElement;
        new (): HTMLEzSkeletonElement;
    };
    interface HTMLEzTabElement extends Components.EzTab, HTMLStencilElement {
    }
    var HTMLEzTabElement: {
        prototype: HTMLEzTabElement;
        new (): HTMLEzTabElement;
    };
    interface HTMLEzTableElement extends Components.EzTable, HTMLStencilElement {
    }
    var HTMLEzTableElement: {
        prototype: HTMLEzTableElement;
        new (): HTMLEzTableElement;
    };
    interface HTMLEzTableCellElement extends Components.EzTableCell, HTMLStencilElement {
    }
    var HTMLEzTableCellElement: {
        prototype: HTMLEzTableCellElement;
        new (): HTMLEzTableCellElement;
    };
    interface HTMLEzTableRowElement extends Components.EzTableRow, HTMLStencilElement {
    }
    var HTMLEzTableRowElement: {
        prototype: HTMLEzTableRowElement;
        new (): HTMLEzTableRowElement;
    };
    interface HTMLEzTabsElementEventMap {
        "tabChange": string;
    }
    interface HTMLEzTabsElement extends Components.EzTabs, HTMLStencilElement {
        addEventListener<K extends keyof HTMLEzTabsElementEventMap>(type: K, listener: (this: HTMLEzTabsElement, ev: EzTabsCustomEvent<HTMLEzTabsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLEzTabsElementEventMap>(type: K, listener: (this: HTMLEzTabsElement, ev: EzTabsCustomEvent<HTMLEzTabsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLEzTabsElement: {
        prototype: HTMLEzTabsElement;
        new (): HTMLEzTabsElement;
    };
    interface HTMLElementTagNameMap {
        "ez-accordion": HTMLEzAccordionElement;
        "ez-accordion-item": HTMLEzAccordionItemElement;
        "ez-autocomplete": HTMLEzAutocompleteElement;
        "ez-badge": HTMLEzBadgeElement;
        "ez-banner-slider": HTMLEzBannerSliderElement;
        "ez-blog-card": HTMLEzBlogCardElement;
        "ez-brand-card": HTMLEzBrandCardElement;
        "ez-breadcrumb": HTMLEzBreadcrumbElement;
        "ez-button": HTMLEzButtonElement;
        "ez-collection-card": HTMLEzCollectionCardElement;
        "ez-comment-item-post": HTMLEzCommentItemPostElement;
        "ez-comment-item-product": HTMLEzCommentItemProductElement;
        "ez-dropdown": HTMLEzDropdownElement;
        "ez-dropdown-item": HTMLEzDropdownItemElement;
        "ez-input": HTMLEzInputElement;
        "ez-loading": HTMLEzLoadingElement;
        "ez-modal": HTMLEzModalElement;
        "ez-pagination": HTMLEzPaginationElement;
        "ez-product-card": HTMLEzProductCardElement;
        "ez-range-datepicker": HTMLEzRangeDatepickerElement;
        "ez-sans-item": HTMLEzSansItemElement;
        "ez-sans-list": HTMLEzSansListElement;
        "ez-select": HTMLEzSelectElement;
        "ez-skeleton": HTMLEzSkeletonElement;
        "ez-tab": HTMLEzTabElement;
        "ez-table": HTMLEzTableElement;
        "ez-table-cell": HTMLEzTableCellElement;
        "ez-table-row": HTMLEzTableRowElement;
        "ez-tabs": HTMLEzTabsElement;
    }
}
declare namespace LocalJSX {
    interface EzAccordion {
    }
    interface EzAccordionItem {
        "label"?: string;
        /**
          * @default false
         */
        "open"?: boolean;
    }
    interface EzAutocomplete {
        /**
          * @default 300
         */
        "debounce"?: number;
        /**
          * @default false
         */
        "loading"?: boolean;
        "onSearch"?: (event: EzAutocompleteCustomEvent<string>) => void;
        "onSelection"?: (event: EzAutocompleteCustomEvent<any>) => void;
        /**
          * @default 'جستجو...'
         */
        "placeholder"?: string;
        /**
          * @default []
         */
        "results"?: string | any[];
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface EzBadge {
        "sysBg"?: string;
        "sysColor"?: string;
        /**
          * @default 'default'
         */
        "variant"?: 'default' | 'success' | 'warning' | 'danger' | 'info' | 'custom';
    }
    interface EzBannerSlider {
        /**
          * @default []
         */
        "items"?: string | any[];
        /**
          * @default 'normal'
         */
        "sliderModel"?: 'wide' | 'normal';
    }
    interface EzBlogCard {
        "href"?: string;
        /**
          * @default false
         */
        "isSlide"?: boolean;
    }
    /**
     * EZ Brand Card — displays brand info with hover effects.
     * Used in brand archive and search results.
     * Props (from AJAX endpoint):
     *   - brandId: number - Brand ID
     *   - title: string - Brand name
     *   - slug: string - URL slug for /brand/{slug}
     *   - logo: string - Logo URL
     *   - score: number - Score (0-100)
     *   - reputation: number - Reputation (0-5 scale)
     *   - address: string - Brand address/location
     *   - gameCount: number - Number of games
     */
    interface EzBrandCard {
        /**
          * Brand address/location
         */
        "address"?: string;
        /**
          * Brand ID
         */
        "brandId"?: number;
        /**
          * @deprecated Use `title` instead
         */
        "brandName"?: string;
        /**
          * @deprecated Use `gameCount`
         */
        "count"?: number;
        /**
          * Number of games/products
         */
        "gameCount"?: number;
        /**
          * @deprecated Use `logo`
         */
        "imageSrc"?: string;
        /**
          * @deprecated Use slug-based link
         */
        "link"?: string;
        /**
          * Logo URL (primary)
         */
        "logo"?: string;
        /**
          * @deprecated Use `logo` instead
         */
        "logoUrl"?: string;
        /**
          * @deprecated Use `title`
         */
        "name"?: string;
        /**
          * @deprecated Use `reputation` instead
         */
        "rating"?: number;
        /**
          * Reputation (0-5 scale)
         */
        "reputation"?: number;
        /**
          * Score (0-100 scale)
         */
        "score"?: number;
        /**
          * Brand slug for URL
         */
        "slug"?: string;
        /**
          * Brand title/name (primary)
         */
        "title"?: string;
    }
    interface EzBreadcrumb {
        /**
          * @default []
         */
        "items"?: string | any[];
    }
    interface EzButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "loading"?: boolean;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary' | 'outline' | 'ghost' | 'danger';
        /**
          * @default false
         */
        "wFull"?: boolean;
    }
    interface EzCollectionCard {
        "collectionTitle"?: string;
        /**
          * @default []
         */
        "images"?: string | string[];
        /**
          * @default 0
         */
        "likes"?: number;
        "link"?: string;
    }
    interface EzCommentItemPost {
    }
    interface EzCommentItemProduct {
        /**
          * @default 0
         */
        "rating"?: number;
        /**
          * @default false
         */
        "verified"?: boolean;
    }
    interface EzDropdown {
        /**
          * @default `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="6,9 12,15 18,9"></polyline></svg>`
         */
        "icon"?: string;
        /**
          * @default 'انتخاب کنید'
         */
        "label"?: string;
        "onSelectionChange"?: (event: EzDropdownCustomEvent<any>) => void;
    }
    interface EzDropdownItem {
        "onOptionSelect"?: (event: EzDropdownItemCustomEvent<{ value: any; text: string }>) => void;
        /**
          * @default false
         */
        "selected"?: boolean;
        "value"?: any;
    }
    interface EzInput {
        "label"?: string;
        "name"?: string;
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 'text'
         */
        "type"?: string;
        "value"?: string;
    }
    interface EzLoading {
        /**
          * @default 'text-primary-500'
         */
        "color"?: string;
        "message"?: string;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg' | 'xl';
        /**
          * @default 'spinner'
         */
        "type"?: 'spinner' | 'dots' | 'circle';
    }
    interface EzModal {
        /**
          * @default true
         */
        "closeOnOverlayClick"?: boolean;
        /**
          * @default false
         */
        "isOpen"?: boolean;
        "modalTitle"?: string;
        "onClose"?: (event: EzModalCustomEvent<void>) => void;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg' | 'xl';
    }
    interface EzPagination {
        /**
          * @default 1
         */
        "currentPage"?: number;
        "onPageChange"?: (event: EzPaginationCustomEvent<number>) => void;
        /**
          * @default 1
         */
        "totalPages"?: number;
    }
    interface EzProductCard {
        "address"?: string;
        "href"?: string;
        "imageUrl"?: string;
        /**
          * @default false
         */
        "isSlide"?: boolean;
        "price"?: string;
        "productId"?: string | number;
        /**
          * عنوان محصول (از سرور؛ در HTML به‌صورت product-title پاس داده می‌شود تا با titleٔ رزروشده تداخل نداشته باشد).
         */
        "productTitle"?: string;
        "status"?: string;
    }
    interface EzRangeDatepicker {
        /**
          * انتخاب بازه (true) یا تک روز (false). از HTML: allow-range یا allow-range="false"
          * @default true
         */
        "allowRange"?: string | boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "disabledDates"?: string[];
        "endDate"?: string;
        "maxDate"?: string;
        "minDate"?: string;
        /**
          * @default 'dateRange'
         */
        "name"?: string;
        "onCalendarClosed"?: (event: EzRangeDatepickerCustomEvent<void>) => void;
        "onCalendarOpened"?: (event: EzRangeDatepickerCustomEvent<void>) => void;
        "onDateChanged"?: (event: EzRangeDatepickerCustomEvent<DateChangeDetail>) => void;
        "onDateCleared"?: (event: EzRangeDatepickerCustomEvent<void>) => void;
        /**
          * @default false
         */
        "persianNumbers"?: boolean;
        /**
          * @default 'انتخاب بازه تاریخ'
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "required"?: boolean;
        "startDate"?: string;
        /**
          * @default '#3b82f6'
         */
        "themeColor"?: string;
    }
    interface EzSansItem {
        "session"?: any;
    }
    interface EzSansList {
        /**
          * API endpoint for fetching sessions (e.g. admin-ajax.php?action=ez_sanses or custom).
          * @default ''
         */
        "apiEndpoint"?: string;
        "productId"?: string | number;
    }
    interface EzSelect {
        "label"?: string;
        /**
          * @default 'single'
         */
        "mode"?: 'single' | 'multiple';
        "name"?: string;
        "onSelectionChange"?: (event: EzSelectCustomEvent<any>) => void;
        /**
          * @default []
         */
        "options"?: string | any[];
        /**
          * @default 'انتخاب کنید'
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "searchable"?: boolean;
        "value"?: string | string[];
    }
    /**
     * EZ Skeleton - Placeholder loader for content that's being fetched.
     * Use as a wrapper or with predefined type props for common patterns.
     */
    interface EzSkeleton {
        /**
          * Show animation pulse effect
          * @default true
         */
        "animate"?: boolean;
        /**
          * Number of items to show (for list/card types)
          * @default 3
         */
        "count"?: number;
        /**
          * Predefined skeleton type: card, list, text, avatar
          * @default 'custom'
         */
        "type"?: 'card' | 'list' | 'text' | 'avatar' | 'custom';
    }
    interface EzTab {
        /**
          * @default false
         */
        "active"?: boolean;
        "label"?: string;
        "tabId"?: string;
    }
    interface EzTable {
        "caption"?: string;
        /**
          * @default []
         */
        "columns"?: string | any[];
        /**
          * @default false
         */
        "loading"?: boolean;
        /**
          * @default 5
         */
        "skeletonCount"?: number;
    }
    interface EzTableCell {
    }
    interface EzTableRow {
    }
    interface EzTabs {
        "activeTab"?: string;
        "onTabChange"?: (event: EzTabsCustomEvent<string>) => void;
    }

    interface EzAccordionItemAttributes {
        "label": string;
        "open": boolean;
    }
    interface EzAutocompleteAttributes {
        "placeholder": string;
        "debounce": number;
        "loading": boolean;
        "results": string | any[];
        "value": string;
    }
    interface EzBadgeAttributes {
        "variant": 'default' | 'success' | 'warning' | 'danger' | 'info' | 'custom';
        "sysColor": string;
        "sysBg": string;
    }
    interface EzBannerSliderAttributes {
        "items": string | any[];
        "sliderModel": 'wide' | 'normal';
    }
    interface EzBlogCardAttributes {
        "href": string;
        "isSlide": boolean;
    }
    interface EzBrandCardAttributes {
        "brandId": number;
        "title": string;
        "slug": string;
        "logo": string;
        "score": number;
        "reputation": number;
        "address": string;
        "gameCount": number;
        "brandName": string;
        "logoUrl": string;
        "link": string;
        "rating": number;
        "name": string;
        "imageSrc": string;
        "count": number;
    }
    interface EzBreadcrumbAttributes {
        "items": string | any[];
    }
    interface EzButtonAttributes {
        "variant": 'primary' | 'secondary' | 'outline' | 'ghost' | 'danger';
        "size": 'sm' | 'md' | 'lg';
        "disabled": boolean;
        "loading": boolean;
        "type": 'button' | 'submit' | 'reset';
        "wFull": boolean;
    }
    interface EzCollectionCardAttributes {
        "collectionTitle": string;
        "likes": number;
        "link": string;
        "images": string | string[];
    }
    interface EzCommentItemProductAttributes {
        "rating": number;
        "verified": boolean;
    }
    interface EzDropdownAttributes {
        "label": string;
        "icon": string;
    }
    interface EzDropdownItemAttributes {
        "value": string;
        "selected": boolean;
    }
    interface EzInputAttributes {
        "label": string;
        "type": string;
        "name": string;
        "placeholder": string;
        "value": string;
        "required": boolean;
        "readonly": boolean;
    }
    interface EzLoadingAttributes {
        "type": 'spinner' | 'dots' | 'circle';
        "size": 'sm' | 'md' | 'lg' | 'xl';
        "message": string;
        "color": string;
    }
    interface EzModalAttributes {
        "isOpen": boolean;
        "modalTitle": string;
        "size": 'sm' | 'md' | 'lg' | 'xl';
        "closeOnOverlayClick": boolean;
    }
    interface EzPaginationAttributes {
        "totalPages": number;
        "currentPage": number;
    }
    interface EzProductCardAttributes {
        "productId": string;
        "status": string;
        "href": string;
        "isSlide": boolean;
        "productTitle": string;
        "price": string;
        "imageUrl": string;
        "address": string;
    }
    interface EzRangeDatepickerAttributes {
        "startDate": string;
        "endDate": string;
        "themeColor": string;
        "placeholder": string;
        "minDate": string;
        "maxDate": string;
        "disabled": boolean;
        "required": boolean;
        "name": string;
        "persianNumbers": boolean;
        "allowRange": string;
    }
    interface EzSansItemAttributes {
        "session": string;
    }
    interface EzSansListAttributes {
        "productId": string;
        "apiEndpoint": string;
    }
    interface EzSelectAttributes {
        "name": string;
        "placeholder": string;
        "options": string | any[];
        "value": string | string[];
        "mode": 'single' | 'multiple';
        "searchable": boolean;
        "label": string;
    }
    interface EzSkeletonAttributes {
        "type": 'card' | 'list' | 'text' | 'avatar' | 'custom';
        "count": number;
        "animate": boolean;
    }
    interface EzTabAttributes {
        "tabId": string;
        "label": string;
        "active": boolean;
    }
    interface EzTableAttributes {
        "columns": string | any[];
        "loading": boolean;
        "skeletonCount": number;
        "caption": string;
    }
    interface EzTabsAttributes {
        "activeTab": string;
    }

    interface IntrinsicElements {
        "ez-accordion": EzAccordion;
        "ez-accordion-item": Omit<EzAccordionItem, keyof EzAccordionItemAttributes> & { [K in keyof EzAccordionItem & keyof EzAccordionItemAttributes]?: EzAccordionItem[K] } & { [K in keyof EzAccordionItem & keyof EzAccordionItemAttributes as `attr:${K}`]?: EzAccordionItemAttributes[K] } & { [K in keyof EzAccordionItem & keyof EzAccordionItemAttributes as `prop:${K}`]?: EzAccordionItem[K] };
        "ez-autocomplete": Omit<EzAutocomplete, keyof EzAutocompleteAttributes> & { [K in keyof EzAutocomplete & keyof EzAutocompleteAttributes]?: EzAutocomplete[K] } & { [K in keyof EzAutocomplete & keyof EzAutocompleteAttributes as `attr:${K}`]?: EzAutocompleteAttributes[K] } & { [K in keyof EzAutocomplete & keyof EzAutocompleteAttributes as `prop:${K}`]?: EzAutocomplete[K] };
        "ez-badge": Omit<EzBadge, keyof EzBadgeAttributes> & { [K in keyof EzBadge & keyof EzBadgeAttributes]?: EzBadge[K] } & { [K in keyof EzBadge & keyof EzBadgeAttributes as `attr:${K}`]?: EzBadgeAttributes[K] } & { [K in keyof EzBadge & keyof EzBadgeAttributes as `prop:${K}`]?: EzBadge[K] };
        "ez-banner-slider": Omit<EzBannerSlider, keyof EzBannerSliderAttributes> & { [K in keyof EzBannerSlider & keyof EzBannerSliderAttributes]?: EzBannerSlider[K] } & { [K in keyof EzBannerSlider & keyof EzBannerSliderAttributes as `attr:${K}`]?: EzBannerSliderAttributes[K] } & { [K in keyof EzBannerSlider & keyof EzBannerSliderAttributes as `prop:${K}`]?: EzBannerSlider[K] };
        "ez-blog-card": Omit<EzBlogCard, keyof EzBlogCardAttributes> & { [K in keyof EzBlogCard & keyof EzBlogCardAttributes]?: EzBlogCard[K] } & { [K in keyof EzBlogCard & keyof EzBlogCardAttributes as `attr:${K}`]?: EzBlogCardAttributes[K] } & { [K in keyof EzBlogCard & keyof EzBlogCardAttributes as `prop:${K}`]?: EzBlogCard[K] };
        "ez-brand-card": Omit<EzBrandCard, keyof EzBrandCardAttributes> & { [K in keyof EzBrandCard & keyof EzBrandCardAttributes]?: EzBrandCard[K] } & { [K in keyof EzBrandCard & keyof EzBrandCardAttributes as `attr:${K}`]?: EzBrandCardAttributes[K] } & { [K in keyof EzBrandCard & keyof EzBrandCardAttributes as `prop:${K}`]?: EzBrandCard[K] };
        "ez-breadcrumb": Omit<EzBreadcrumb, keyof EzBreadcrumbAttributes> & { [K in keyof EzBreadcrumb & keyof EzBreadcrumbAttributes]?: EzBreadcrumb[K] } & { [K in keyof EzBreadcrumb & keyof EzBreadcrumbAttributes as `attr:${K}`]?: EzBreadcrumbAttributes[K] } & { [K in keyof EzBreadcrumb & keyof EzBreadcrumbAttributes as `prop:${K}`]?: EzBreadcrumb[K] };
        "ez-button": Omit<EzButton, keyof EzButtonAttributes> & { [K in keyof EzButton & keyof EzButtonAttributes]?: EzButton[K] } & { [K in keyof EzButton & keyof EzButtonAttributes as `attr:${K}`]?: EzButtonAttributes[K] } & { [K in keyof EzButton & keyof EzButtonAttributes as `prop:${K}`]?: EzButton[K] };
        "ez-collection-card": Omit<EzCollectionCard, keyof EzCollectionCardAttributes> & { [K in keyof EzCollectionCard & keyof EzCollectionCardAttributes]?: EzCollectionCard[K] } & { [K in keyof EzCollectionCard & keyof EzCollectionCardAttributes as `attr:${K}`]?: EzCollectionCardAttributes[K] } & { [K in keyof EzCollectionCard & keyof EzCollectionCardAttributes as `prop:${K}`]?: EzCollectionCard[K] };
        "ez-comment-item-post": EzCommentItemPost;
        "ez-comment-item-product": Omit<EzCommentItemProduct, keyof EzCommentItemProductAttributes> & { [K in keyof EzCommentItemProduct & keyof EzCommentItemProductAttributes]?: EzCommentItemProduct[K] } & { [K in keyof EzCommentItemProduct & keyof EzCommentItemProductAttributes as `attr:${K}`]?: EzCommentItemProductAttributes[K] } & { [K in keyof EzCommentItemProduct & keyof EzCommentItemProductAttributes as `prop:${K}`]?: EzCommentItemProduct[K] };
        "ez-dropdown": Omit<EzDropdown, keyof EzDropdownAttributes> & { [K in keyof EzDropdown & keyof EzDropdownAttributes]?: EzDropdown[K] } & { [K in keyof EzDropdown & keyof EzDropdownAttributes as `attr:${K}`]?: EzDropdownAttributes[K] } & { [K in keyof EzDropdown & keyof EzDropdownAttributes as `prop:${K}`]?: EzDropdown[K] };
        "ez-dropdown-item": Omit<EzDropdownItem, keyof EzDropdownItemAttributes> & { [K in keyof EzDropdownItem & keyof EzDropdownItemAttributes]?: EzDropdownItem[K] } & { [K in keyof EzDropdownItem & keyof EzDropdownItemAttributes as `attr:${K}`]?: EzDropdownItemAttributes[K] } & { [K in keyof EzDropdownItem & keyof EzDropdownItemAttributes as `prop:${K}`]?: EzDropdownItem[K] };
        "ez-input": Omit<EzInput, keyof EzInputAttributes> & { [K in keyof EzInput & keyof EzInputAttributes]?: EzInput[K] } & { [K in keyof EzInput & keyof EzInputAttributes as `attr:${K}`]?: EzInputAttributes[K] } & { [K in keyof EzInput & keyof EzInputAttributes as `prop:${K}`]?: EzInput[K] };
        "ez-loading": Omit<EzLoading, keyof EzLoadingAttributes> & { [K in keyof EzLoading & keyof EzLoadingAttributes]?: EzLoading[K] } & { [K in keyof EzLoading & keyof EzLoadingAttributes as `attr:${K}`]?: EzLoadingAttributes[K] } & { [K in keyof EzLoading & keyof EzLoadingAttributes as `prop:${K}`]?: EzLoading[K] };
        "ez-modal": Omit<EzModal, keyof EzModalAttributes> & { [K in keyof EzModal & keyof EzModalAttributes]?: EzModal[K] } & { [K in keyof EzModal & keyof EzModalAttributes as `attr:${K}`]?: EzModalAttributes[K] } & { [K in keyof EzModal & keyof EzModalAttributes as `prop:${K}`]?: EzModal[K] };
        "ez-pagination": Omit<EzPagination, keyof EzPaginationAttributes> & { [K in keyof EzPagination & keyof EzPaginationAttributes]?: EzPagination[K] } & { [K in keyof EzPagination & keyof EzPaginationAttributes as `attr:${K}`]?: EzPaginationAttributes[K] } & { [K in keyof EzPagination & keyof EzPaginationAttributes as `prop:${K}`]?: EzPagination[K] };
        "ez-product-card": Omit<EzProductCard, keyof EzProductCardAttributes> & { [K in keyof EzProductCard & keyof EzProductCardAttributes]?: EzProductCard[K] } & { [K in keyof EzProductCard & keyof EzProductCardAttributes as `attr:${K}`]?: EzProductCardAttributes[K] } & { [K in keyof EzProductCard & keyof EzProductCardAttributes as `prop:${K}`]?: EzProductCard[K] };
        "ez-range-datepicker": Omit<EzRangeDatepicker, keyof EzRangeDatepickerAttributes> & { [K in keyof EzRangeDatepicker & keyof EzRangeDatepickerAttributes]?: EzRangeDatepicker[K] } & { [K in keyof EzRangeDatepicker & keyof EzRangeDatepickerAttributes as `attr:${K}`]?: EzRangeDatepickerAttributes[K] } & { [K in keyof EzRangeDatepicker & keyof EzRangeDatepickerAttributes as `prop:${K}`]?: EzRangeDatepicker[K] };
        "ez-sans-item": Omit<EzSansItem, keyof EzSansItemAttributes> & { [K in keyof EzSansItem & keyof EzSansItemAttributes]?: EzSansItem[K] } & { [K in keyof EzSansItem & keyof EzSansItemAttributes as `attr:${K}`]?: EzSansItemAttributes[K] } & { [K in keyof EzSansItem & keyof EzSansItemAttributes as `prop:${K}`]?: EzSansItem[K] };
        "ez-sans-list": Omit<EzSansList, keyof EzSansListAttributes> & { [K in keyof EzSansList & keyof EzSansListAttributes]?: EzSansList[K] } & { [K in keyof EzSansList & keyof EzSansListAttributes as `attr:${K}`]?: EzSansListAttributes[K] } & { [K in keyof EzSansList & keyof EzSansListAttributes as `prop:${K}`]?: EzSansList[K] };
        "ez-select": Omit<EzSelect, keyof EzSelectAttributes> & { [K in keyof EzSelect & keyof EzSelectAttributes]?: EzSelect[K] } & { [K in keyof EzSelect & keyof EzSelectAttributes as `attr:${K}`]?: EzSelectAttributes[K] } & { [K in keyof EzSelect & keyof EzSelectAttributes as `prop:${K}`]?: EzSelect[K] };
        "ez-skeleton": Omit<EzSkeleton, keyof EzSkeletonAttributes> & { [K in keyof EzSkeleton & keyof EzSkeletonAttributes]?: EzSkeleton[K] } & { [K in keyof EzSkeleton & keyof EzSkeletonAttributes as `attr:${K}`]?: EzSkeletonAttributes[K] } & { [K in keyof EzSkeleton & keyof EzSkeletonAttributes as `prop:${K}`]?: EzSkeleton[K] };
        "ez-tab": Omit<EzTab, keyof EzTabAttributes> & { [K in keyof EzTab & keyof EzTabAttributes]?: EzTab[K] } & { [K in keyof EzTab & keyof EzTabAttributes as `attr:${K}`]?: EzTabAttributes[K] } & { [K in keyof EzTab & keyof EzTabAttributes as `prop:${K}`]?: EzTab[K] };
        "ez-table": Omit<EzTable, keyof EzTableAttributes> & { [K in keyof EzTable & keyof EzTableAttributes]?: EzTable[K] } & { [K in keyof EzTable & keyof EzTableAttributes as `attr:${K}`]?: EzTableAttributes[K] } & { [K in keyof EzTable & keyof EzTableAttributes as `prop:${K}`]?: EzTable[K] };
        "ez-table-cell": EzTableCell;
        "ez-table-row": EzTableRow;
        "ez-tabs": Omit<EzTabs, keyof EzTabsAttributes> & { [K in keyof EzTabs & keyof EzTabsAttributes]?: EzTabs[K] } & { [K in keyof EzTabs & keyof EzTabsAttributes as `attr:${K}`]?: EzTabsAttributes[K] } & { [K in keyof EzTabs & keyof EzTabsAttributes as `prop:${K}`]?: EzTabs[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ez-accordion": LocalJSX.IntrinsicElements["ez-accordion"] & JSXBase.HTMLAttributes<HTMLEzAccordionElement>;
            "ez-accordion-item": LocalJSX.IntrinsicElements["ez-accordion-item"] & JSXBase.HTMLAttributes<HTMLEzAccordionItemElement>;
            "ez-autocomplete": LocalJSX.IntrinsicElements["ez-autocomplete"] & JSXBase.HTMLAttributes<HTMLEzAutocompleteElement>;
            "ez-badge": LocalJSX.IntrinsicElements["ez-badge"] & JSXBase.HTMLAttributes<HTMLEzBadgeElement>;
            "ez-banner-slider": LocalJSX.IntrinsicElements["ez-banner-slider"] & JSXBase.HTMLAttributes<HTMLEzBannerSliderElement>;
            "ez-blog-card": LocalJSX.IntrinsicElements["ez-blog-card"] & JSXBase.HTMLAttributes<HTMLEzBlogCardElement>;
            /**
             * EZ Brand Card — displays brand info with hover effects.
             * Used in brand archive and search results.
             * Props (from AJAX endpoint):
             *   - brandId: number - Brand ID
             *   - title: string - Brand name
             *   - slug: string - URL slug for /brand/{slug}
             *   - logo: string - Logo URL
             *   - score: number - Score (0-100)
             *   - reputation: number - Reputation (0-5 scale)
             *   - address: string - Brand address/location
             *   - gameCount: number - Number of games
             */
            "ez-brand-card": LocalJSX.IntrinsicElements["ez-brand-card"] & JSXBase.HTMLAttributes<HTMLEzBrandCardElement>;
            "ez-breadcrumb": LocalJSX.IntrinsicElements["ez-breadcrumb"] & JSXBase.HTMLAttributes<HTMLEzBreadcrumbElement>;
            "ez-button": LocalJSX.IntrinsicElements["ez-button"] & JSXBase.HTMLAttributes<HTMLEzButtonElement>;
            "ez-collection-card": LocalJSX.IntrinsicElements["ez-collection-card"] & JSXBase.HTMLAttributes<HTMLEzCollectionCardElement>;
            "ez-comment-item-post": LocalJSX.IntrinsicElements["ez-comment-item-post"] & JSXBase.HTMLAttributes<HTMLEzCommentItemPostElement>;
            "ez-comment-item-product": LocalJSX.IntrinsicElements["ez-comment-item-product"] & JSXBase.HTMLAttributes<HTMLEzCommentItemProductElement>;
            "ez-dropdown": LocalJSX.IntrinsicElements["ez-dropdown"] & JSXBase.HTMLAttributes<HTMLEzDropdownElement>;
            "ez-dropdown-item": LocalJSX.IntrinsicElements["ez-dropdown-item"] & JSXBase.HTMLAttributes<HTMLEzDropdownItemElement>;
            "ez-input": LocalJSX.IntrinsicElements["ez-input"] & JSXBase.HTMLAttributes<HTMLEzInputElement>;
            "ez-loading": LocalJSX.IntrinsicElements["ez-loading"] & JSXBase.HTMLAttributes<HTMLEzLoadingElement>;
            "ez-modal": LocalJSX.IntrinsicElements["ez-modal"] & JSXBase.HTMLAttributes<HTMLEzModalElement>;
            "ez-pagination": LocalJSX.IntrinsicElements["ez-pagination"] & JSXBase.HTMLAttributes<HTMLEzPaginationElement>;
            "ez-product-card": LocalJSX.IntrinsicElements["ez-product-card"] & JSXBase.HTMLAttributes<HTMLEzProductCardElement>;
            "ez-range-datepicker": LocalJSX.IntrinsicElements["ez-range-datepicker"] & JSXBase.HTMLAttributes<HTMLEzRangeDatepickerElement>;
            "ez-sans-item": LocalJSX.IntrinsicElements["ez-sans-item"] & JSXBase.HTMLAttributes<HTMLEzSansItemElement>;
            "ez-sans-list": LocalJSX.IntrinsicElements["ez-sans-list"] & JSXBase.HTMLAttributes<HTMLEzSansListElement>;
            "ez-select": LocalJSX.IntrinsicElements["ez-select"] & JSXBase.HTMLAttributes<HTMLEzSelectElement>;
            /**
             * EZ Skeleton - Placeholder loader for content that's being fetched.
             * Use as a wrapper or with predefined type props for common patterns.
             */
            "ez-skeleton": LocalJSX.IntrinsicElements["ez-skeleton"] & JSXBase.HTMLAttributes<HTMLEzSkeletonElement>;
            "ez-tab": LocalJSX.IntrinsicElements["ez-tab"] & JSXBase.HTMLAttributes<HTMLEzTabElement>;
            "ez-table": LocalJSX.IntrinsicElements["ez-table"] & JSXBase.HTMLAttributes<HTMLEzTableElement>;
            "ez-table-cell": LocalJSX.IntrinsicElements["ez-table-cell"] & JSXBase.HTMLAttributes<HTMLEzTableCellElement>;
            "ez-table-row": LocalJSX.IntrinsicElements["ez-table-row"] & JSXBase.HTMLAttributes<HTMLEzTableRowElement>;
            "ez-tabs": LocalJSX.IntrinsicElements["ez-tabs"] & JSXBase.HTMLAttributes<HTMLEzTabsElement>;
        }
    }
}
